from pyspark.sql.types import StructType, StructField, IntegerType, DoubleType, StringType

def get_average_spark_schema():

    schema = StructType([
        StructField('league_id', IntegerType(), True),
        StructField('starter_status', StringType(), True),
        StructField('gk_shots_on_target_against', DoubleType(), True),
        StructField('gk_goals_against', DoubleType(), True),
        StructField('gk_saves', DoubleType(), True),
        StructField('gk_save_pct', DoubleType(), True),
        StructField('gk_psxg', DoubleType(), True),
        StructField('gk_passes_completed_launched', DoubleType(), True),
        StructField('gk_passes_launched', DoubleType(), True),
        StructField('gk_passes_pct_launched', DoubleType(), True),
        StructField('gk_passes', DoubleType(), True),
        StructField('gk_passes_throws', DoubleType(), True),
        StructField('gk_pct_passes_launched', DoubleType(), True),
        StructField('gk_passes_length_avg', DoubleType(), True),
        StructField('gk_goal_kicks', DoubleType(), True),
        StructField('gk_pct_goal_kicks_launched', DoubleType(), True),
        StructField('gk_goal_kick_length_avg', DoubleType(), True),
        StructField('gk_crosses', DoubleType(), True),
        StructField('gk_crosses_stopped', DoubleType(), True),
        StructField('gk_crosses_stopped_pct', DoubleType(), True),
        StructField('gk_def_actions_outside_pen_area', DoubleType(), True),
        StructField('gk_avg_distance_def_actions', DoubleType(), True),
        StructField('goals', DoubleType(), True),
        StructField('assists', DoubleType(), True),
        StructField('pens_made', DoubleType(), True),
        StructField('pens_att', DoubleType(), True),
        StructField('shots', DoubleType(), True),
        StructField('shots_on_target', DoubleType(), True),
        StructField('cards_yellow', DoubleType(), True),
        StructField('cards_red', DoubleType(), True),
        StructField('touches', DoubleType(), True),
        StructField('tackles', DoubleType(), True),
        StructField('interceptions', DoubleType(), True),
        StructField('blocks', DoubleType(), True),
        StructField('xg', DoubleType(), True),
        StructField('npxg', DoubleType(), True),
        StructField('xg_assist', DoubleType(), True),
        StructField('sca', DoubleType(), True),
        StructField('gca', DoubleType(), True),
        StructField('passes_completed', DoubleType(), True),
        StructField('passes', DoubleType(), True),
        StructField('passes_pct', DoubleType(), True),
        StructField('progressive_passes', DoubleType(), True),
        StructField('carries', DoubleType(), True),
        StructField('progressive_carries', DoubleType(), True),
        StructField('take_ons', DoubleType(), True),
        StructField('take_ons_won', DoubleType(), True),
        StructField('passes_total_distance', DoubleType(), True),
        StructField('passes_progressive_distance', DoubleType(), True),
        StructField('passes_completed_short', DoubleType(), True),
        StructField('passes_short', DoubleType(), True),
        StructField('passes_pct_short', DoubleType(), True),
        StructField('passes_completed_medium', DoubleType(), True),
        StructField('passes_medium', DoubleType(), True),
        StructField('passes_pct_medium', DoubleType(), True),
        StructField('passes_completed_long', DoubleType(), True),
        StructField('passes_long', DoubleType(), True),
        StructField('passes_pct_long', DoubleType(), True),
        StructField('xg_assists', DoubleType(), True),
        StructField('pass_xa', DoubleType(), True),
        StructField('assisted_shots', DoubleType(), True),
        StructField('passes_into_final_third', DoubleType(), True),
        StructField('passes_into_penalty_area', DoubleType(), True),
        StructField('crosses_into_penalty_area', DoubleType(), True),
        StructField('passes_live', DoubleType(), True),
        StructField('passes_dead', DoubleType(), True),
        StructField('passes_free_kicks', DoubleType(), True),
        StructField('through_balls', DoubleType(), True),
        StructField('passes_switches', DoubleType(), True),
        StructField('crosses', DoubleType(), True),
        StructField('throw_ins', DoubleType(), True),
        StructField('corner_kicks', DoubleType(), True),
        StructField('corner_kicks_in', DoubleType(), True),
        StructField('corner_kicks_out', DoubleType(), True),
        StructField('corner_kicks_straight', DoubleType(), True),
        StructField('passes_offsides', DoubleType(), True),
        StructField('passes_blocked', DoubleType(), True),
        StructField('tackles_won', DoubleType(), True),
        StructField('tackles_def_3rd', DoubleType(), True),
        StructField('tackles_mid_3rd', DoubleType(), True),
        StructField('tackles_att_3rd', DoubleType(), True),
        StructField('challenge_tackles', DoubleType(), True),
        StructField('challenges', DoubleType(), True),
        StructField('challenge_tackles_pct', DoubleType(), True),
        StructField('challenged_lost', DoubleType(), True),
        StructField('blocked_shots', DoubleType(), True),
        StructField('blocked_passes', DoubleType(), True),
        StructField('tackles_interceptions', DoubleType(), True),
        StructField('clearances', DoubleType(), True),
        StructField('errors', DoubleType(), True),
        StructField('touches_def_pen_area', DoubleType(), True),
        StructField('touches_def_3rd', DoubleType(), True),
        StructField('touches_mid_3rd', DoubleType(), True),
        StructField('touches_att_3rd', DoubleType(), True),
        StructField('touches_att_pen_area', DoubleType(), True),
        StructField('touches_live_ball', DoubleType(), True),
        StructField('take_ons_won_pct', DoubleType(), True),
        StructField('take_ons_tackled', DoubleType(), True),
        StructField('take_ons_tackled_pct', DoubleType(), True),
        StructField('carries_distance', DoubleType(), True),
        StructField('carries_progressive_distance', DoubleType(), True),
        StructField('carries_into_final_third', DoubleType(), True),
        StructField('carries_into_penalty_area', DoubleType(), True),
        StructField('miscontrols', DoubleType(), True),
        StructField('dispossessed', DoubleType(), True),
        StructField('passes_received', DoubleType(), True),
        StructField('progressive_passes_received', DoubleType(), True),
        StructField('cards_yellow_red', DoubleType(), True),
        StructField('fouls', DoubleType(), True),
        StructField('fouled', DoubleType(), True),
        StructField('offsides', DoubleType(), True),
        StructField('pens_won', DoubleType(), True),
        StructField('pens_conceded', DoubleType(), True),
        StructField('own_goals', DoubleType(), True),
        StructField('ball_recoveries', DoubleType(), True),
        StructField('aerials_won', DoubleType(), True),
        StructField('aerials_lost', DoubleType(), True),
        StructField('aerials_won_pct', DoubleType(), True)
    ])
    return schema



def get_average_spark_schema_by_positions_gk():

    schema = StructType([
        StructField('league_id', IntegerType(), True),
        StructField('position_player', IntegerType(), True),
        StructField('type_of_stat', StringType(), True),
        StructField('starter_status', StringType(), True),
        StructField('gk_shots_on_target_against', DoubleType(), True),
        StructField('gk_goals_against', DoubleType(), True),
        StructField('gk_saves', DoubleType(), True),
        StructField('gk_save_pct', DoubleType(), True),
        StructField('gk_psxg', DoubleType(), True),
        StructField('gk_passes_completed_launched', DoubleType(), True),
        StructField('gk_passes_launched', DoubleType(), True),
        StructField('gk_passes_pct_launched', DoubleType(), True),
        StructField('gk_passes', DoubleType(), True),
        StructField('gk_passes_throws', DoubleType(), True),
        StructField('gk_pct_passes_launched', DoubleType(), True),
        StructField('gk_passes_length_avg', DoubleType(), True),
        StructField('gk_goal_kicks', DoubleType(), True),
        StructField('gk_pct_goal_kicks_launched', DoubleType(), True),
        StructField('gk_goal_kick_length_avg', DoubleType(), True),
        StructField('gk_crosses', DoubleType(), True),
        StructField('gk_crosses_stopped', DoubleType(), True),
        StructField('gk_crosses_stopped_pct', DoubleType(), True),
        StructField('gk_def_actions_outside_pen_area', DoubleType(), True),
        StructField('gk_avg_distance_def_actions', DoubleType(), True),
        StructField('goals', DoubleType(), True),
        StructField('assists', DoubleType(), True),
        StructField('pens_made', DoubleType(), True),
        StructField('pens_att', DoubleType(), True),
        StructField('shots', DoubleType(), True),
        StructField('shots_on_target', DoubleType(), True),
        StructField('cards_yellow', DoubleType(), True),
        StructField('cards_red', DoubleType(), True),
        StructField('touches', DoubleType(), True),
        StructField('tackles', DoubleType(), True),
        StructField('interceptions', DoubleType(), True),
        StructField('blocks', DoubleType(), True),
        StructField('xg', DoubleType(), True),
        StructField('npxg', DoubleType(), True),
        StructField('xg_assist', DoubleType(), True),
        StructField('sca', DoubleType(), True),
        StructField('gca', DoubleType(), True),
        StructField('passes_completed', DoubleType(), True),
        StructField('passes', DoubleType(), True),
        StructField('passes_pct', DoubleType(), True),
        StructField('progressive_passes', DoubleType(), True),
        StructField('carries', DoubleType(), True),
        StructField('progressive_carries', DoubleType(), True),
        StructField('take_ons', DoubleType(), True),
        StructField('take_ons_won', DoubleType(), True),
        StructField('passes_total_distance', DoubleType(), True),
        StructField('passes_progressive_distance', DoubleType(), True),
        StructField('passes_completed_short', DoubleType(), True),
        StructField('passes_short', DoubleType(), True),
        StructField('passes_pct_short', DoubleType(), True),
        StructField('passes_completed_medium', DoubleType(), True),
        StructField('passes_medium', DoubleType(), True),
        StructField('passes_pct_medium', DoubleType(), True),
        StructField('passes_completed_long', DoubleType(), True),
        StructField('passes_long', DoubleType(), True),
        StructField('passes_pct_long', DoubleType(), True),
        StructField('xg_assists', DoubleType(), True),
        StructField('pass_xa', DoubleType(), True),
        StructField('assisted_shots', DoubleType(), True),
        StructField('passes_into_final_third', DoubleType(), True),
        StructField('passes_into_penalty_area', DoubleType(), True),
        StructField('crosses_into_penalty_area', DoubleType(), True),
        StructField('passes_live', DoubleType(), True),
        StructField('passes_dead', DoubleType(), True),
        StructField('passes_free_kicks', DoubleType(), True),
        StructField('through_balls', DoubleType(), True),
        StructField('passes_switches', DoubleType(), True),
        StructField('crosses', DoubleType(), True),
        StructField('throw_ins', DoubleType(), True),
        StructField('corner_kicks', DoubleType(), True),
        StructField('corner_kicks_in', DoubleType(), True),
        StructField('corner_kicks_out', DoubleType(), True),
        StructField('corner_kicks_straight', DoubleType(), True),
        StructField('passes_offsides', DoubleType(), True),
        StructField('passes_blocked', DoubleType(), True),
        StructField('tackles_won', DoubleType(), True),
        StructField('tackles_def_3rd', DoubleType(), True),
        StructField('tackles_mid_3rd', DoubleType(), True),
        StructField('tackles_att_3rd', DoubleType(), True),
        StructField('challenge_tackles', DoubleType(), True),
        StructField('challenges', DoubleType(), True),
        StructField('challenge_tackles_pct', DoubleType(), True),
        StructField('challenged_lost', DoubleType(), True),
        StructField('blocked_shots', DoubleType(), True),
        StructField('blocked_passes', DoubleType(), True),
        StructField('tackles_interceptions', DoubleType(), True),
        StructField('clearances', DoubleType(), True),
        StructField('errors', DoubleType(), True),
        StructField('touches_def_pen_area', DoubleType(), True),
        StructField('touches_def_3rd', DoubleType(), True),
        StructField('touches_mid_3rd', DoubleType(), True),
        StructField('touches_att_3rd', DoubleType(), True),
        StructField('touches_att_pen_area', DoubleType(), True),
        StructField('touches_live_ball', DoubleType(), True),
        StructField('take_ons_won_pct', DoubleType(), True),
        StructField('take_ons_tackled', DoubleType(), True),
        StructField('take_ons_tackled_pct', DoubleType(), True),
        StructField('carries_distance', DoubleType(), True),
        StructField('carries_progressive_distance', DoubleType(), True),
        StructField('carries_into_final_third', DoubleType(), True),
        StructField('carries_into_penalty_area', DoubleType(), True),
        StructField('miscontrols', DoubleType(), True),
        StructField('dispossessed', DoubleType(), True),
        StructField('passes_received', DoubleType(), True),
        StructField('progressive_passes_received', DoubleType(), True),
        StructField('cards_yellow_red', DoubleType(), True),
        StructField('fouls', DoubleType(), True),
        StructField('fouled', DoubleType(), True),
        StructField('offsides', DoubleType(), True),
        StructField('pens_won', DoubleType(), True),
        StructField('pens_conceded', DoubleType(), True),
        StructField('own_goals', DoubleType(), True),
        StructField('ball_recoveries', DoubleType(), True),
        StructField('aerials_won', DoubleType(), True),
        StructField('aerials_lost', DoubleType(), True),
        StructField('aerials_won_pct', DoubleType(), True),

    ])
    return schema



def get_average_spark_schema_by_positions_field_player():

    schema = StructType([
        StructField('league_id', IntegerType(), True),
        StructField('position_player', IntegerType(), True),
        StructField('type_of_stat', StringType(), True),
        StructField('starter_status', StringType(), True),
        StructField('goals', DoubleType(), True),
        StructField('assists', DoubleType(), True),
        StructField('pens_made', DoubleType(), True),
        StructField('pens_att', DoubleType(), True),
        StructField('shots', DoubleType(), True),
        StructField('shots_on_target', DoubleType(), True),
        StructField('cards_yellow', DoubleType(), True),
        StructField('cards_red', DoubleType(), True),
        StructField('touches', DoubleType(), True),
        StructField('tackles', DoubleType(), True),
        StructField('interceptions', DoubleType(), True),
        StructField('blocks', DoubleType(), True),
        StructField('xg', DoubleType(), True),
        StructField('npxg', DoubleType(), True),
        StructField('xg_assist', DoubleType(), True),
        StructField('sca', DoubleType(), True),
        StructField('gca', DoubleType(), True),
        StructField('passes_completed', DoubleType(), True),
        StructField('passes', DoubleType(), True),
        StructField('passes_pct', DoubleType(), True),
        StructField('progressive_passes', DoubleType(), True),
        StructField('carries', DoubleType(), True),
        StructField('progressive_carries', DoubleType(), True),
        StructField('take_ons', DoubleType(), True),
        StructField('take_ons_won', DoubleType(), True),
        StructField('passes_total_distance', DoubleType(), True),
        StructField('passes_progressive_distance', DoubleType(), True),
        StructField('passes_completed_short', DoubleType(), True),
        StructField('passes_short', DoubleType(), True),
        StructField('passes_pct_short', DoubleType(), True),
        StructField('passes_completed_medium', DoubleType(), True),
        StructField('passes_medium', DoubleType(), True),
        StructField('passes_pct_medium', DoubleType(), True),
        StructField('passes_completed_long', DoubleType(), True),
        StructField('passes_long', DoubleType(), True),
        StructField('passes_pct_long', DoubleType(), True),
        StructField('xg_assists', DoubleType(), True),
        StructField('pass_xa', DoubleType(), True),
        StructField('assisted_shots', DoubleType(), True),
        StructField('passes_into_final_third', DoubleType(), True),
        StructField('passes_into_penalty_area', DoubleType(), True),
        StructField('crosses_into_penalty_area', DoubleType(), True),
        StructField('passes_live', DoubleType(), True),
        StructField('passes_dead', DoubleType(), True),
        StructField('passes_free_kicks', DoubleType(), True),
        StructField('through_balls', DoubleType(), True),
        StructField('passes_switches', DoubleType(), True),
        StructField('crosses', DoubleType(), True),
        StructField('throw_ins', DoubleType(), True),
        StructField('corner_kicks', DoubleType(), True),
        StructField('corner_kicks_in', DoubleType(), True),
        StructField('corner_kicks_out', DoubleType(), True),
        StructField('corner_kicks_straight', DoubleType(), True),
        StructField('passes_offsides', DoubleType(), True),
        StructField('passes_blocked', DoubleType(), True),
        StructField('tackles_won', DoubleType(), True),
        StructField('tackles_def_3rd', DoubleType(), True),
        StructField('tackles_mid_3rd', DoubleType(), True),
        StructField('tackles_att_3rd', DoubleType(), True),
        StructField('challenge_tackles', DoubleType(), True),
        StructField('challenges', DoubleType(), True),
        StructField('challenge_tackles_pct', DoubleType(), True),
        StructField('challenged_lost', DoubleType(), True),
        StructField('blocked_shots', DoubleType(), True),
        StructField('blocked_passes', DoubleType(), True),
        StructField('tackles_interceptions', DoubleType(), True),
        StructField('clearances', DoubleType(), True),
        StructField('errors', DoubleType(), True),
        StructField('touches_def_pen_area', DoubleType(), True),
        StructField('touches_def_3rd', DoubleType(), True),
        StructField('touches_mid_3rd', DoubleType(), True),
        StructField('touches_att_3rd', DoubleType(), True),
        StructField('touches_att_pen_area', DoubleType(), True),
        StructField('touches_live_ball', DoubleType(), True),
        StructField('take_ons_won_pct', DoubleType(), True),
        StructField('take_ons_tackled', DoubleType(), True),
        StructField('take_ons_tackled_pct', DoubleType(), True),
        StructField('carries_distance', DoubleType(), True),
        StructField('carries_progressive_distance', DoubleType(), True),
        StructField('carries_into_final_third', DoubleType(), True),
        StructField('carries_into_penalty_area', DoubleType(), True),
        StructField('miscontrols', DoubleType(), True),
        StructField('dispossessed', DoubleType(), True),
        StructField('passes_received', DoubleType(), True),
        StructField('progressive_passes_received', DoubleType(), True),
        StructField('cards_yellow_red', DoubleType(), True),
        StructField('fouls', DoubleType(), True),
        StructField('fouled', DoubleType(), True),
        StructField('offsides', DoubleType(), True),
        StructField('pens_won', DoubleType(), True),
        StructField('pens_conceded', DoubleType(), True),
        StructField('own_goals', DoubleType(), True),
        StructField('ball_recoveries', DoubleType(), True),
        StructField('aerials_won', DoubleType(), True),
        StructField('aerials_lost', DoubleType(), True),
        StructField('aerials_won_pct', DoubleType(), True),
    
    ])
    return schema










# Tabla a crear en la base de datos
"""
CREATE TABLE avg_teams_player_stats (
    id int PRIMARY KEY AUTO_INCREMENT,
    league_id INT,
    team_id INT,
    starter_status ENUM('starter', 'substitute'),
    goals FLOAT,
    assists FLOAT,
    gk_shots_on_target_against FLOAT,
    gk_goals_against FLOAT,
    gk_saves FLOAT,
    gk_save_pct FLOAT,
    gk_psxg FLOAT,
    gk_passes_completed_launched FLOAT,
    gk_passes_launched FLOAT,
    gk_passes_pct_launched FLOAT,
    gk_passes FLOAT,
    gk_passes_throws FLOAT,
    gk_pct_passes_launched FLOAT,
    gk_passes_length_avg FLOAT,
    gk_goal_kicks FLOAT,
    gk_pct_goal_kicks_launched FLOAT,
    gk_goal_kick_length_avg FLOAT,
    gk_crosses FLOAT,
    gk_crosses_stopped FLOAT,
    gk_crosses_stopped_pct FLOAT,
    gk_def_actions_outside_pen_area FLOAT,
    gk_avg_distance_def_actions FLOAT,
    goals FLOAT,
    assists FLOAT,
    pens_made FLOAT,
    pens_att FLOAT,
    shots FLOAT,
    shots_on_target FLOAT,
    cards_yellow FLOAT,
    cards_red FLOAT,
    touches FLOAT,
    tackles FLOAT,
    interceptions FLOAT,
    blocks FLOAT,
    xg FLOAT,
    npxg FLOAT,
    xg_assist FLOAT,
    sca FLOAT,
    gca FLOAT,
    passes_completed FLOAT,
    passes FLOAT,
    passes_pct FLOAT,
    progressive_passes FLOAT,
    carries FLOAT,
    progressive_carries FLOAT,
    take_ons FLOAT,
    take_ons_won FLOAT,
    passes_total_distance FLOAT,
    passes_progressive_distance FLOAT,
    passes_completed_short FLOAT,
    passes_short FLOAT,
    passes_pct_short FLOAT,
    passes_completed_medium FLOAT,
    passes_medium FLOAT,
    passes_pct_medium FLOAT,
    passes_completed_long FLOAT,
    passes_long FLOAT,
    passes_pct_long FLOAT,
    xg_assists FLOAT,
    pass_xa FLOAT,
    assisted_shots FLOAT,
    passes_into_final_third FLOAT,
    passes_into_penalty_area FLOAT,
    crosses_into_penalty_area FLOAT,
    passes_live FLOAT,
    passes_dead FLOAT,
    passes_free_kicks FLOAT,
    through_balls FLOAT,
    passes_switches FLOAT,
    crosses FLOAT,
    throw_ins FLOAT,
    corner_kicks FLOAT,
    corner_kicks_in FLOAT,
    corner_kicks_out FLOAT,
    corner_kicks_straight FLOAT,
    passes_offsides FLOAT,
    passes_blocked FLOAT,
    tackles_won FLOAT,
    tackles_def_3rd FLOAT,
    tackles_mid_3rd FLOAT,
    tackles_att_3rd FLOAT,
    challenge_tackles FLOAT,
    challenges FLOAT,
    challenge_tackles_pct FLOAT,
    challenged_lost FLOAT,
    blocked_shots FLOAT,
    blocked_passes FLOAT,
    tackles_interceptions FLOAT,
    clearances FLOAT,
    errors FLOAT,
    touches_def_pen_area FLOAT,
    touches_def_3rd FLOAT,
    touches_mid_3rd FLOAT,
    touches_att_3rd FLOAT,
    touches_att_pen_area FLOAT,
    touches_live_ball FLOAT,
    take_ons_won_pct FLOAT,
    take_ons_tackled FLOAT,
    take_ons_tackled_pct FLOAT,
    carries_distance FLOAT,
    carries_progressive_distance FLOAT,
    carries_into_final_third FLOAT,
    carries_into_penalty_area FLOAT,
    miscontrols FLOAT,
    dispossessed FLOAT,
    passes_received FLOAT,
    progressive_passes_received FLOAT,
    cards_yellow_red FLOAT,
    fouls FLOAT,
    fouled FLOAT,
    offsides FLOAT,
    pens_won FLOAT,
    pens_conceded FLOAT,
    own_goals FLOAT,
    ball_recoveries FLOAT,
    aerials_won FLOAT,
    aerials_lost FLOAT,
    aerials_won_pct FLOAT

);

ALTER TABLE avg_teams_player_stats ADD FOREIGN KEY (league_id) REFERENCES tournament(tournament_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE avg_teams_player_stats ADD FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE ON UPDATE CASCADE;


"""



"""
CREATE TABLE avg_teams_player_stats_by_basic_positions (
    id int PRIMARY KEY AUTO_INCREMENT,
    league_id INT,
    team_id INT,
    position_player INT, 
    type_of_stat ENUM('avg', 'desv'),
    starter_status ENUM('starter', 'substitute'),
    gk_shots_on_target_against FLOAT default 0,
    gk_goals_against FLOAT default 0,
    gk_saves FLOAT default 0,
    gk_save_pct FLOAT default 0,
    gk_psxg FLOAT default 0,
    gk_passes_completed_launched FLOAT default 0,
    gk_passes_launched FLOAT default 0,
    gk_passes_pct_launched FLOAT default 0,
    gk_passes FLOAT default 0,
    gk_passes_throws FLOAT default 0,
    gk_pct_passes_launched FLOAT default 0,
    gk_passes_length_avg FLOAT default 0,
    gk_goal_kicks FLOAT default 0,
    gk_pct_goal_kicks_launched FLOAT default 0,
    gk_goal_kick_length_avg FLOAT default 0,
    gk_crosses FLOAT default 0,
    gk_crosses_stopped FLOAT default 0,
    gk_crosses_stopped_pct FLOAT default 0,
    gk_def_actions_outside_pen_area FLOAT default 0,
    gk_avg_distance_def_actions FLOAT default 0,
    goals FLOAT,
    assists FLOAT,
    pens_made FLOAT,
    pens_att FLOAT,
    shots FLOAT,
    shots_on_target FLOAT,
    cards_yellow FLOAT,
    cards_red FLOAT,
    touches FLOAT,
    tackles FLOAT,
    interceptions FLOAT,
    blocks FLOAT,
    xg FLOAT,
    npxg FLOAT,
    xg_assist FLOAT,
    sca FLOAT,
    gca FLOAT,
    passes_completed FLOAT,
    passes FLOAT,
    passes_pct FLOAT,
    progressive_passes FLOAT,
    carries FLOAT,
    progressive_carries FLOAT,
    take_ons FLOAT,
    take_ons_won FLOAT,
    passes_total_distance FLOAT,
    passes_progressive_distance FLOAT,
    passes_completed_short FLOAT,
    passes_short FLOAT,
    passes_pct_short FLOAT,
    passes_completed_medium FLOAT,
    passes_medium FLOAT,
    passes_pct_medium FLOAT,
    passes_completed_long FLOAT,
    passes_long FLOAT,
    passes_pct_long FLOAT,
    xg_assists FLOAT,
    pass_xa FLOAT,
    assisted_shots FLOAT,
    passes_into_final_third FLOAT,
    passes_into_penalty_area FLOAT,
    crosses_into_penalty_area FLOAT,
    passes_live FLOAT,
    passes_dead FLOAT,
    passes_free_kicks FLOAT,
    through_balls FLOAT,
    passes_switches FLOAT,
    crosses FLOAT,
    throw_ins FLOAT,
    corner_kicks FLOAT,
    corner_kicks_in FLOAT,
    corner_kicks_out FLOAT,
    corner_kicks_straight FLOAT,
    passes_offsides FLOAT,
    passes_blocked FLOAT,
    tackles_won FLOAT,
    tackles_def_3rd FLOAT,
    tackles_mid_3rd FLOAT,
    tackles_att_3rd FLOAT,
    challenge_tackles FLOAT,
    challenges FLOAT,
    challenge_tackles_pct FLOAT,
    challenged_lost FLOAT,
    blocked_shots FLOAT,
    blocked_passes FLOAT,
    tackles_interceptions FLOAT,
    clearances FLOAT,
    errors FLOAT,
    touches_def_pen_area FLOAT,
    touches_def_3rd FLOAT,
    touches_mid_3rd FLOAT,
    touches_att_3rd FLOAT,
    touches_att_pen_area FLOAT,
    touches_live_ball FLOAT,
    take_ons_won_pct FLOAT,
    take_ons_tackled FLOAT,
    take_ons_tackled_pct FLOAT,
    carries_distance FLOAT,
    carries_progressive_distance FLOAT,
    carries_into_final_third FLOAT,
    carries_into_penalty_area FLOAT,
    miscontrols FLOAT,
    dispossessed FLOAT,
    passes_received FLOAT,
    progressive_passes_received FLOAT,
    cards_yellow_red FLOAT,
    fouls FLOAT,
    fouled FLOAT,
    offsides FLOAT,
    pens_won FLOAT,
    pens_conceded FLOAT,
    own_goals FLOAT,
    ball_recoveries FLOAT,
    aerials_won FLOAT,
    aerials_lost FLOAT,
    aerials_won_pct FLOAT,
    goals_pens_per90 FLOAT,
    xa FLOAT,
);

ALTER TABLE avg_teams_player_stats_by_basic_positions ADD FOREIGN KEY (league_id) REFERENCES tournament(tournament_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE avg_teams_player_stats_by_basic_positions ADD FOREIGN KEY (position_player) REFERENCES position_category(category_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE avg_teams_player_stats_by_basic_positions ADD FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE ON UPDATE CASCADE;


crear una columna
ALTER TABLE avg_player_stats_by_basic_positions ADD COLUMN goals FLOAT;
ALTER TABLE avg_player_stats_by_basic_positions ADD COLUMN assists FLOAT;


"""




"""
CREATE TABLE avg_teams_player_stats_by_specific_positions (
    id int PRIMARY KEY AUTO_INCREMENT,
    league_id INT,
    team_id INT,
    position_player INT, 
    type_of_stat ENUM('avg', 'desv'),
    starter_status ENUM('starter', 'substitute'),
    gk_shots_on_target_against FLOAT default 0,
    gk_goals_against FLOAT default 0,
    gk_saves FLOAT default 0,
    gk_save_pct FLOAT default 0,
    gk_psxg FLOAT default 0,
    gk_passes_completed_launched FLOAT default 0,
    gk_passes_launched FLOAT default 0,
    gk_passes_pct_launched FLOAT default 0,
    gk_passes FLOAT default 0,
    gk_passes_throws FLOAT default 0,
    gk_pct_passes_launched FLOAT default 0,
    gk_passes_length_avg FLOAT default 0,
    gk_goal_kicks FLOAT default 0,
    gk_pct_goal_kicks_launched FLOAT default 0,
    gk_goal_kick_length_avg FLOAT default 0,
    gk_crosses FLOAT default 0,
    gk_crosses_stopped FLOAT default 0,
    gk_crosses_stopped_pct FLOAT default 0,
    gk_def_actions_outside_pen_area FLOAT default 0,
    gk_avg_distance_def_actions FLOAT default 0,
    goals FLOAT  default 0,
    assists FLOAT  default 0,
    pens_made FLOAT default 0,
    pens_att FLOAT default 0,
    shots FLOAT default 0,
    shots_on_target FLOAT default 0,
    cards_yellow FLOAT,
    cards_red FLOAT,
    touches FLOAT,
    tackles FLOAT,
    interceptions FLOAT,
    blocks FLOAT,
    xg FLOAT,
    npxg FLOAT,
    xg_assist FLOAT,
    sca FLOAT,
    gca FLOAT,
    passes_completed FLOAT,
    passes FLOAT,
    passes_pct FLOAT,
    progressive_passes FLOAT,
    carries FLOAT,
    progressive_carries FLOAT,
    take_ons FLOAT,
    take_ons_won FLOAT,
    passes_total_distance FLOAT,
    passes_progressive_distance FLOAT,
    passes_completed_short FLOAT,
    passes_short FLOAT,
    passes_pct_short FLOAT,
    passes_completed_medium FLOAT,
    passes_medium FLOAT,
    passes_pct_medium FLOAT,
    passes_completed_long FLOAT,
    passes_long FLOAT,
    passes_pct_long FLOAT,
    xg_assists FLOAT,
    pass_xa FLOAT,
    assisted_shots FLOAT,
    passes_into_final_third FLOAT,
    passes_into_penalty_area FLOAT,
    crosses_into_penalty_area FLOAT,
    passes_live FLOAT,
    passes_dead FLOAT,
    passes_free_kicks FLOAT,
    through_balls FLOAT,
    passes_switches FLOAT,
    crosses FLOAT,
    throw_ins FLOAT,
    corner_kicks FLOAT,
    corner_kicks_in FLOAT,
    corner_kicks_out FLOAT,
    corner_kicks_straight FLOAT,
    passes_offsides FLOAT,
    passes_blocked FLOAT,
    tackles_won FLOAT,
    tackles_def_3rd FLOAT,
    tackles_mid_3rd FLOAT,
    tackles_att_3rd FLOAT,
    challenge_tackles FLOAT,
    challenges FLOAT,
    challenge_tackles_pct FLOAT,
    challenged_lost FLOAT,
    blocked_shots FLOAT,
    blocked_passes FLOAT,
    tackles_interceptions FLOAT,
    clearances FLOAT,
    errors FLOAT,
    touches_def_pen_area FLOAT,
    touches_def_3rd FLOAT,
    touches_mid_3rd FLOAT,
    touches_att_3rd FLOAT,
    touches_att_pen_area FLOAT,
    touches_live_ball FLOAT,
    take_ons_won_pct FLOAT,
    take_ons_tackled FLOAT,
    take_ons_tackled_pct FLOAT,
    carries_distance FLOAT,
    carries_progressive_distance FLOAT,
    carries_into_final_third FLOAT,
    carries_into_penalty_area FLOAT,
    miscontrols FLOAT,
    dispossessed FLOAT,
    passes_received FLOAT,
    progressive_passes_received FLOAT,
    cards_yellow_red FLOAT,
    fouls FLOAT,
    fouled FLOAT,
    offsides FLOAT,
    pens_won FLOAT,
    pens_conceded FLOAT,
    own_goals FLOAT,
    ball_recoveries FLOAT,
    aerials_won FLOAT,
    aerials_lost FLOAT,
    aerials_won_pct FLOAT,
    goals_pens_per90 FLOAT,
    xa FLOAT,
);

ALTER TABLE avg_teams_player_stats_by_specific_positions ADD FOREIGN KEY (league_id) REFERENCES tournament(tournament_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE avg_teams_player_stats_by_specific_positions ADD FOREIGN KEY (position_player) REFERENCES positions_specifics_by_category(specific_position_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE avg_teams_player_stats_by_specific_positions ADD FOREIGN KEY (team_id) REFERENCES team(team_id) ON DELETE CASCADE ON UPDATE CASCADE;

"""





