

services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend_football_stats
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  frontend:
    build:
      context: ./football-stats-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./football-stats-frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend


volumes:
  mysql_data:

