// Traducciones.ts
export const positionTranslation: Record<string, string> = {
    "no_existencia": "Puntuación Básica",
    "defenders": "Defensa",
    "midfielders": "Centrocampista",
    "forwards": "Delantero",
    "goalkeepers": "Portero",

};

export const specificPositionTranslation: Record<string, string> = {
    "no_existencia": "Puntuación General",
    "goalkeeper": "Portero",
    "fullback": "Defensa",
    "central_defender": "Defensa Central",
    "center_midfielder": "Centrocampista Central",
    "lateral_midfielder": "Centrocampista Lateral",
    "defensive_midfielder": "Centrocampista Defensivo",
    "offensive_midfielder": "Centrocampista Ofensivo",
    "winger": "Extremo",
    "forward": "Delantero",
};


export const gameModeTranslation: Record<string, string> = {
    "no_existencia": "Puntuación General",
    "bloque_bajo": "Bloque Bajo",
    "bloque_medio": "Bloque Medio",
    "presion_alta": "Presión Alta",
    "juego_por_bandas": "Juego por Bandas",
    "tiki_taka": "Tiki Taka",
    "contraataque": "Contraataque",
};

export const statTranslation: Record<string, string> = {
  "touches": "Toques",
  "shots": "Tiros",
  "xg": "Goles esperados (xG)",
  "passes_completed": "Pases completados",
  "passes": "Pases ",
  "passes_pct": "Precisión de pase (%)",
  "progressive_passes": "Pases progresivos",
  "carries": "Conducciones",
  "take_ons": "Regates intentados",

  "touches_def_pen_area": "Toques en área defensiva",
  "touches_def_3rd": "Toques en tercio defensivo",
  "touches_mid_3rd": "Toques en tercio medio",
  "touches_att_3rd": "Toques en tercio ofensivo",
  "touches_att_pen_area": "Toques en área ofensiva",
  "touches_live_ball": "Toques en juego",
  "take_ons_won_pct": "Éxito en regates (%)",
  "carries_distance": "Distancia conducida",
  "carries_progressive_distance": "Distancia progresiva conducida",
  "progressive_distance": "Distancia progresiva",
  "miscontrols": "Pérdidas de control",
  "dispossessed": "Desposeído",
  "passes_received": "Pases recibidos",
  "progressive_passes_received": "Pases progresivos recibidos",

  "passes_live": "Pases en juego",
  "passes_dead": "Pases en balón parado",
  "passes_free_kicks": "Pases en tiros libres",
  "through_balls": "Pases filtrados",
  "passes_switches": "Cambios de juego",
  "crosses": "Centros",
  "throw_ins": "Saques de banda",
  "passes_offsides": "Pases en fuera de juego",

  "passes_total_distance": "Distancia total de pase",
  "passes_progressive_distance": "Distancia progresiva de pase",
  "passes_completed_short": "Pases cortos completados",
  "passes_short": "Pases cortos",
  "passes_pct_short": "Precisión en pases cortos (%)",
  "passes_completed_medium": "Pases medios completados",
  "passes_medium": "Pases medios",
  "passes_pct_medium": "Precisión en pases medios (%)",
  "passes_completed_long": "Pases largos completados",
  "passes_long": "Pases largos",
  "passes_pct_long": "Precisión en pases largos (%)",
  "xg_assists": "Asistencias esperadas (xA)",
  "assisted_shots": "Tiros asistidos",
  "passes_into_final_third": "Pases al último tercio",
  "passes_into_penalty_area": "Pases al área",
  "crosses_into_penalty_area": "Centros al área",

  "fouls": "Faltas cometidas",
  "fouled": "Faltas recibidas",
  "cards_yellow": "Tarjetas amarillas",
  "cards_red": "Tarjetas rojas",
  "offsides": "Fueras de juego",
  "interceptions": "Intercepciones",
  "tackles_won": "Entradas ganadas",
  "ball_recoveries": "Recuperaciones",
  "aerials_won": "Duelos aéreos ganados",
  "aerials_lost": "Duelos aéreos perdidos",
  "aerials_won_pct": "Éxito en duelos aéreos (%)",

  "tackles": "Entradas",
  "tackles_def_3rd": "Entradas en tercio defensivo",
  "tackles_mid_3rd": "Entradas en tercio medio",
  "tackles_att_3rd": "Entradas en tercio ofensivo",
  "challenges_tackles": "Retos y entradas",
  "challenges": "Retos defensivos",
  "challenges_tackles_pct": "Éxito en retos (%)",
  "challenged_lost": "Retos perdidos",
  "blocks": "Bloqueos",
  "blocked_shots": "Tiros bloqueados",
  "tacles_interceptions": "Entradas e intercepciones",
  "clearences": "Despejes",
  "errors": "Errores defensivos",

  "gk_shots_on_target_against": "Tiros a puerta recibidos",
  "gk_goals_against": "Goles encajados",
  "gk_saves": "Paradas",
  "gk_save_pct": "Porcentaje de paradas",
  "gk_psxg": "xG post-parada (PSxG)",
  "gk_passes_completed_launched": "Pases largos completados",
  "gk_passes_launched": "Pases largos",
  "gk_passes_pct_launched": "Precisión en pases largos (%)",
  "gk_passes": "Pases totales",
  "gk_passes_throws": "Saques con la mano",
  "gk_pct_passes_launched": "Pases largos (%)",
  "gk_passes_length_avg": "Longitud media de pase",
  "gk_goal_kicks": "Saques de puerta",
  "gk_pct_goal_kicks_launched": "Saque largo (%)",
  "gk_goal_kick_length_avg": "Longitud media de saque",
  "gk_crosses": "Centros recibidos",
  "gk_crosses_stopped": "Centros atrapados",
  "gk_crosses_stopped_pct": "Éxito atrapando centros (%)",
  "gk_def_actions_outside_pen_area": "Acciones fuera del área",
  "gk_avg_distance_def_actions": "Distancia media de acciones defensivas"
};
